package org.yuesi.cjzbx.datacenter.model.mapper;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import org.yuesi.cjzbx.datacenter.model.MarketTradedaily;
import org.yuesi.cjzbx.datacenter.model.MarketTradedailyCriteria.Criteria;
import org.yuesi.cjzbx.datacenter.model.MarketTradedailyCriteria.Criterion;
import org.yuesi.cjzbx.datacenter.model.MarketTradedailyCriteria;

public class MarketTradedailySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    public String countByExample(MarketTradedailyCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("market_tradedaily");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    public String deleteByExample(MarketTradedailyCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("market_tradedaily");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    public String insertSelective(MarketTradedaily record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("market_tradedaily");
        
        if (record.getTradedate() != null) {
            sql.VALUES("tradedate", "#{tradedate,jdbcType=DATE}");
        }
        
        if (record.getCodeid() != null) {
            sql.VALUES("codeid", "#{codeid,jdbcType=VARCHAR}");
        }
        
        if (record.getOpen() != null) {
            sql.VALUES("open", "#{open,jdbcType=DECIMAL}");
        }
        
        if (record.getHigh() != null) {
            sql.VALUES("high", "#{high,jdbcType=DECIMAL}");
        }
        
        if (record.getLow() != null) {
            sql.VALUES("low", "#{low,jdbcType=DECIMAL}");
        }
        
        if (record.getClose() != null) {
            sql.VALUES("close", "#{close,jdbcType=DECIMAL}");
        }
        
        if (record.getVolume() != null) {
            sql.VALUES("volume", "#{volume,jdbcType=INTEGER}");
        }
        
        if (record.getAmount() != null) {
            sql.VALUES("amount", "#{amount,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    public String selectByExample(MarketTradedailyCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("tradedate");
        } else {
            sql.SELECT("tradedate");
        }
        sql.SELECT("codeid");
        sql.SELECT("open");
        sql.SELECT("high");
        sql.SELECT("low");
        sql.SELECT("close");
        sql.SELECT("volume");
        sql.SELECT("amount");
        sql.FROM("market_tradedaily");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MarketTradedaily record = (MarketTradedaily) parameter.get("record");
        MarketTradedailyCriteria example = (MarketTradedailyCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("market_tradedaily");
        
        if (record.getTradedate() != null) {
            sql.SET("tradedate = #{record.tradedate,jdbcType=DATE}");
        }
        
        if (record.getCodeid() != null) {
            sql.SET("codeid = #{record.codeid,jdbcType=VARCHAR}");
        }
        
        if (record.getOpen() != null) {
            sql.SET("open = #{record.open,jdbcType=DECIMAL}");
        }
        
        if (record.getHigh() != null) {
            sql.SET("high = #{record.high,jdbcType=DECIMAL}");
        }
        
        if (record.getLow() != null) {
            sql.SET("low = #{record.low,jdbcType=DECIMAL}");
        }
        
        if (record.getClose() != null) {
            sql.SET("close = #{record.close,jdbcType=DECIMAL}");
        }
        
        if (record.getVolume() != null) {
            sql.SET("volume = #{record.volume,jdbcType=INTEGER}");
        }
        
        if (record.getAmount() != null) {
            sql.SET("amount = #{record.amount,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("market_tradedaily");
        
        sql.SET("tradedate = #{record.tradedate,jdbcType=DATE}");
        sql.SET("codeid = #{record.codeid,jdbcType=VARCHAR}");
        sql.SET("open = #{record.open,jdbcType=DECIMAL}");
        sql.SET("high = #{record.high,jdbcType=DECIMAL}");
        sql.SET("low = #{record.low,jdbcType=DECIMAL}");
        sql.SET("close = #{record.close,jdbcType=DECIMAL}");
        sql.SET("volume = #{record.volume,jdbcType=INTEGER}");
        sql.SET("amount = #{record.amount,jdbcType=INTEGER}");
        
        MarketTradedailyCriteria example = (MarketTradedailyCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(MarketTradedaily record) {
        SQL sql = new SQL();
        sql.UPDATE("market_tradedaily");
        
        if (record.getOpen() != null) {
            sql.SET("open = #{open,jdbcType=DECIMAL}");
        }
        
        if (record.getHigh() != null) {
            sql.SET("high = #{high,jdbcType=DECIMAL}");
        }
        
        if (record.getLow() != null) {
            sql.SET("low = #{low,jdbcType=DECIMAL}");
        }
        
        if (record.getClose() != null) {
            sql.SET("close = #{close,jdbcType=DECIMAL}");
        }
        
        if (record.getVolume() != null) {
            sql.SET("volume = #{volume,jdbcType=INTEGER}");
        }
        
        if (record.getAmount() != null) {
            sql.SET("amount = #{amount,jdbcType=INTEGER}");
        }
        
        sql.WHERE("tradedate = #{tradedate,jdbcType=DATE}");
        sql.WHERE("codeid = #{codeid,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, MarketTradedailyCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}