package org.yuesi.cjzbx.datacenter.model.mapper;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import org.yuesi.cjzbx.datacenter.model.MarketTradeCal;
import org.yuesi.cjzbx.datacenter.model.MarketTradeCalCriteria.Criteria;
import org.yuesi.cjzbx.datacenter.model.MarketTradeCalCriteria.Criterion;
import org.yuesi.cjzbx.datacenter.model.MarketTradeCalCriteria;

public class MarketTradeCalSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradecal
     *
     * @mbg.generated Wed May 24 22:01:38 CST 2017
     */
    public String countByExample(MarketTradeCalCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("market_tradecal");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradecal
     *
     * @mbg.generated Wed May 24 22:01:38 CST 2017
     */
    public String deleteByExample(MarketTradeCalCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("market_tradecal");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradecal
     *
     * @mbg.generated Wed May 24 22:01:38 CST 2017
     */
    public String insertSelective(MarketTradeCal record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("market_tradecal");
        
        if (record.getExchangecd() != null) {
            sql.VALUES("exchangeCD", "#{exchangecd,jdbcType=VARCHAR}");
        }
        
        if (record.getCalendardate() != null) {
            sql.VALUES("calendarDate", "#{calendardate,jdbcType=DATE}");
        }
        
        if (record.getIsopen() != null) {
            sql.VALUES("isOpen", "#{isopen,jdbcType=BIT}");
        }
        
        if (record.getIsweekend() != null) {
            sql.VALUES("isWeekEnd", "#{isweekend,jdbcType=BIT}");
        }
        
        if (record.getIsmonthend() != null) {
            sql.VALUES("isMonthEnd", "#{ismonthend,jdbcType=BIT}");
        }
        
        if (record.getIsquarterend() != null) {
            sql.VALUES("isQuarterEnd", "#{isquarterend,jdbcType=BIT}");
        }
        
        if (record.getIsyearend() != null) {
            sql.VALUES("isYearEnd", "#{isyearend,jdbcType=BIT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradecal
     *
     * @mbg.generated Wed May 24 22:01:38 CST 2017
     */
    public String selectByExample(MarketTradeCalCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("exchangeCD");
        } else {
            sql.SELECT("exchangeCD");
        }
        sql.SELECT("calendarDate");
        sql.SELECT("isOpen");
        sql.SELECT("isWeekEnd");
        sql.SELECT("isMonthEnd");
        sql.SELECT("isQuarterEnd");
        sql.SELECT("isYearEnd");
        sql.FROM("market_tradecal");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradecal
     *
     * @mbg.generated Wed May 24 22:01:38 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MarketTradeCal record = (MarketTradeCal) parameter.get("record");
        MarketTradeCalCriteria example = (MarketTradeCalCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("market_tradecal");
        
        if (record.getExchangecd() != null) {
            sql.SET("exchangeCD = #{record.exchangecd,jdbcType=VARCHAR}");
        }
        
        if (record.getCalendardate() != null) {
            sql.SET("calendarDate = #{record.calendardate,jdbcType=DATE}");
        }
        
        if (record.getIsopen() != null) {
            sql.SET("isOpen = #{record.isopen,jdbcType=BIT}");
        }
        
        if (record.getIsweekend() != null) {
            sql.SET("isWeekEnd = #{record.isweekend,jdbcType=BIT}");
        }
        
        if (record.getIsmonthend() != null) {
            sql.SET("isMonthEnd = #{record.ismonthend,jdbcType=BIT}");
        }
        
        if (record.getIsquarterend() != null) {
            sql.SET("isQuarterEnd = #{record.isquarterend,jdbcType=BIT}");
        }
        
        if (record.getIsyearend() != null) {
            sql.SET("isYearEnd = #{record.isyearend,jdbcType=BIT}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradecal
     *
     * @mbg.generated Wed May 24 22:01:38 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("market_tradecal");
        
        sql.SET("exchangeCD = #{record.exchangecd,jdbcType=VARCHAR}");
        sql.SET("calendarDate = #{record.calendardate,jdbcType=DATE}");
        sql.SET("isOpen = #{record.isopen,jdbcType=BIT}");
        sql.SET("isWeekEnd = #{record.isweekend,jdbcType=BIT}");
        sql.SET("isMonthEnd = #{record.ismonthend,jdbcType=BIT}");
        sql.SET("isQuarterEnd = #{record.isquarterend,jdbcType=BIT}");
        sql.SET("isYearEnd = #{record.isyearend,jdbcType=BIT}");
        
        MarketTradeCalCriteria example = (MarketTradeCalCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradecal
     *
     * @mbg.generated Wed May 24 22:01:38 CST 2017
     */
    public String updateByPrimaryKeySelective(MarketTradeCal record) {
        SQL sql = new SQL();
        sql.UPDATE("market_tradecal");
        
        if (record.getIsopen() != null) {
            sql.SET("isOpen = #{isopen,jdbcType=BIT}");
        }
        
        if (record.getIsweekend() != null) {
            sql.SET("isWeekEnd = #{isweekend,jdbcType=BIT}");
        }
        
        if (record.getIsmonthend() != null) {
            sql.SET("isMonthEnd = #{ismonthend,jdbcType=BIT}");
        }
        
        if (record.getIsquarterend() != null) {
            sql.SET("isQuarterEnd = #{isquarterend,jdbcType=BIT}");
        }
        
        if (record.getIsyearend() != null) {
            sql.SET("isYearEnd = #{isyearend,jdbcType=BIT}");
        }
        
        sql.WHERE("exchangeCD = #{exchangecd,jdbcType=VARCHAR}");
        sql.WHERE("calendarDate = #{calendardate,jdbcType=DATE}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradecal
     *
     * @mbg.generated Wed May 24 22:01:38 CST 2017
     */
    protected void applyWhere(SQL sql, MarketTradeCalCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}