package org.yuesi.cjzbx.datacenter.model.mapper;

import org.apache.ibatis.jdbc.SQL;
import org.yuesi.cjzbx.datacenter.model.MarketTradeDaily;

public class MarketTradeDailySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public String insertSelective(MarketTradeDaily record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("market_tradedaily");
        
        if (record.getTradedate() != null) {
            sql.VALUES("tradedate", "#{tradedate,jdbcType=DATE}");
        }
        
        if (record.getCodeid() != null) {
            sql.VALUES("codeid", "#{codeid,jdbcType=VARCHAR}");
        }
        
        if (record.getOpen() != null) {
            sql.VALUES("open", "#{open,jdbcType=DECIMAL}");
        }
        
        if (record.getHigh() != null) {
            sql.VALUES("high", "#{high,jdbcType=DECIMAL}");
        }
        
        if (record.getLow() != null) {
            sql.VALUES("low", "#{low,jdbcType=DECIMAL}");
        }
        
        if (record.getClose() != null) {
            sql.VALUES("close", "#{close,jdbcType=DECIMAL}");
        }
        
        if (record.getVolume() != null) {
            sql.VALUES("volume", "#{volume,jdbcType=INTEGER}");
        }
        
        if (record.getAmount() != null) {
            sql.VALUES("amount", "#{amount,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public String updateByPrimaryKeySelective(MarketTradeDaily record) {
        SQL sql = new SQL();
        sql.UPDATE("market_tradedaily");
        
        if (record.getOpen() != null) {
            sql.SET("open = #{open,jdbcType=DECIMAL}");
        }
        
        if (record.getHigh() != null) {
            sql.SET("high = #{high,jdbcType=DECIMAL}");
        }
        
        if (record.getLow() != null) {
            sql.SET("low = #{low,jdbcType=DECIMAL}");
        }
        
        if (record.getClose() != null) {
            sql.SET("close = #{close,jdbcType=DECIMAL}");
        }
        
        if (record.getVolume() != null) {
            sql.SET("volume = #{volume,jdbcType=INTEGER}");
        }
        
        if (record.getAmount() != null) {
            sql.SET("amount = #{amount,jdbcType=INTEGER}");
        }
        
        sql.WHERE("tradedate = #{tradedate,jdbcType=DATE}");
        sql.WHERE("codeid = #{codeid,jdbcType=VARCHAR}");
        
        return sql.toString();
    }
}