package org.yuesi.cjzbx.datacenter.model;

import java.math.BigDecimal;
import java.util.Date;

public class MarketTradeDaily {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradedaily.tradedate
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private Date tradedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradedaily.codeid
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private String codeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradedaily.open
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private BigDecimal open;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradedaily.high
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private BigDecimal high;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradedaily.low
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private BigDecimal low;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradedaily.close
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private BigDecimal close;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradedaily.volume
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private Integer volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradedaily.amount
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private Integer amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradedaily.tradedate
     *
     * @return the value of market_tradedaily.tradedate
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public Date getTradedate() {
        return tradedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradedaily.tradedate
     *
     * @param tradedate the value for market_tradedaily.tradedate
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setTradedate(Date tradedate) {
        this.tradedate = tradedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradedaily.codeid
     *
     * @return the value of market_tradedaily.codeid
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public String getCodeid() {
        return codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradedaily.codeid
     *
     * @param codeid the value for market_tradedaily.codeid
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setCodeid(String codeid) {
        this.codeid = codeid == null ? null : codeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradedaily.open
     *
     * @return the value of market_tradedaily.open
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public BigDecimal getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradedaily.open
     *
     * @param open the value for market_tradedaily.open
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setOpen(BigDecimal open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradedaily.high
     *
     * @return the value of market_tradedaily.high
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public BigDecimal getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradedaily.high
     *
     * @param high the value for market_tradedaily.high
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setHigh(BigDecimal high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradedaily.low
     *
     * @return the value of market_tradedaily.low
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public BigDecimal getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradedaily.low
     *
     * @param low the value for market_tradedaily.low
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setLow(BigDecimal low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradedaily.close
     *
     * @return the value of market_tradedaily.close
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public BigDecimal getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradedaily.close
     *
     * @param close the value for market_tradedaily.close
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setClose(BigDecimal close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradedaily.volume
     *
     * @return the value of market_tradedaily.volume
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public Integer getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradedaily.volume
     *
     * @param volume the value for market_tradedaily.volume
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setVolume(Integer volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradedaily.amount
     *
     * @return the value of market_tradedaily.amount
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradedaily.amount
     *
     * @param amount the value for market_tradedaily.amount
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}