package org.yuesi.cjzbx.datacenter.model;

import java.util.Date;

public class MarketTradeCal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradecal.exchangeCD
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private String exchangecd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradecal.calendarDate
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private Date calendardate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradecal.isOpen
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private Boolean isopen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradecal.isWeekEnd
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private Boolean isweekend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradecal.isMonthEnd
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private Boolean ismonthend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradecal.isQuarterEnd
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private Boolean isquarterend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column market_tradecal.isYearEnd
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    private Boolean isyearend;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradecal.exchangeCD
     *
     * @return the value of market_tradecal.exchangeCD
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public String getExchangecd() {
        return exchangecd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradecal.exchangeCD
     *
     * @param exchangecd the value for market_tradecal.exchangeCD
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setExchangecd(String exchangecd) {
        this.exchangecd = exchangecd == null ? null : exchangecd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradecal.calendarDate
     *
     * @return the value of market_tradecal.calendarDate
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public Date getCalendardate() {
        return calendardate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradecal.calendarDate
     *
     * @param calendardate the value for market_tradecal.calendarDate
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setCalendardate(Date calendardate) {
        this.calendardate = calendardate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradecal.isOpen
     *
     * @return the value of market_tradecal.isOpen
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public Boolean getIsopen() {
        return isopen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradecal.isOpen
     *
     * @param isopen the value for market_tradecal.isOpen
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setIsopen(Boolean isopen) {
        this.isopen = isopen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradecal.isWeekEnd
     *
     * @return the value of market_tradecal.isWeekEnd
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public Boolean getIsweekend() {
        return isweekend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradecal.isWeekEnd
     *
     * @param isweekend the value for market_tradecal.isWeekEnd
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setIsweekend(Boolean isweekend) {
        this.isweekend = isweekend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradecal.isMonthEnd
     *
     * @return the value of market_tradecal.isMonthEnd
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public Boolean getIsmonthend() {
        return ismonthend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradecal.isMonthEnd
     *
     * @param ismonthend the value for market_tradecal.isMonthEnd
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setIsmonthend(Boolean ismonthend) {
        this.ismonthend = ismonthend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradecal.isQuarterEnd
     *
     * @return the value of market_tradecal.isQuarterEnd
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public Boolean getIsquarterend() {
        return isquarterend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradecal.isQuarterEnd
     *
     * @param isquarterend the value for market_tradecal.isQuarterEnd
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setIsquarterend(Boolean isquarterend) {
        this.isquarterend = isquarterend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column market_tradecal.isYearEnd
     *
     * @return the value of market_tradecal.isYearEnd
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public Boolean getIsyearend() {
        return isyearend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column market_tradecal.isYearEnd
     *
     * @param isyearend the value for market_tradecal.isYearEnd
     *
     * @mbg.generated Mon Mar 06 22:04:53 CST 2017
     */
    public void setIsyearend(Boolean isyearend) {
        this.isyearend = isyearend;
    }
}