package org.yuesi.cjzbx.datacenter.domain.mapper;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.yuesi.cjzbx.datacenter.domain.MarketTradeDaily;
import org.yuesi.cjzbx.datacenter.domain.MarketTradeDailyCriteria;

public interface MarketTradeDailyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    @SelectProvider(type=MarketTradeDailySqlProvider.class, method="countByExample")
    long countByExample(MarketTradeDailyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    @DeleteProvider(type=MarketTradeDailySqlProvider.class, method="deleteByExample")
    int deleteByExample(MarketTradeDailyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    @Delete({
        "delete from market_tradedaily",
        "where tradedate = #{tradedate,jdbcType=DATE}",
          "and codeid = #{codeid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("tradedate") Date tradedate, @Param("codeid") String codeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    @Insert({
        "insert into market_tradedaily (tradedate, codeid, ",
        "open, high, low, ",
        "close, volume, amount)",
        "values (#{tradedate,jdbcType=DATE}, #{codeid,jdbcType=VARCHAR}, ",
        "#{open,jdbcType=DECIMAL}, #{high,jdbcType=DECIMAL}, #{low,jdbcType=DECIMAL}, ",
        "#{close,jdbcType=DECIMAL}, #{volume,jdbcType=INTEGER}, #{amount,jdbcType=INTEGER})"
    })
    int insert(MarketTradeDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    @InsertProvider(type=MarketTradeDailySqlProvider.class, method="insertSelective")
    int insertSelective(MarketTradeDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    @SelectProvider(type=MarketTradeDailySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="tradedate", property="tradedate", jdbcType=JdbcType.DATE, id=true),
        @Result(column="codeid", property="codeid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="open", property="open", jdbcType=JdbcType.DECIMAL),
        @Result(column="high", property="high", jdbcType=JdbcType.DECIMAL),
        @Result(column="low", property="low", jdbcType=JdbcType.DECIMAL),
        @Result(column="close", property="close", jdbcType=JdbcType.DECIMAL),
        @Result(column="volume", property="volume", jdbcType=JdbcType.INTEGER),
        @Result(column="amount", property="amount", jdbcType=JdbcType.INTEGER)
    })
    List<MarketTradeDaily> selectByExample(MarketTradeDailyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "tradedate, codeid, open, high, low, close, volume, amount",
        "from market_tradedaily",
        "where tradedate = #{tradedate,jdbcType=DATE}",
          "and codeid = #{codeid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="tradedate", property="tradedate", jdbcType=JdbcType.DATE, id=true),
        @Result(column="codeid", property="codeid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="open", property="open", jdbcType=JdbcType.DECIMAL),
        @Result(column="high", property="high", jdbcType=JdbcType.DECIMAL),
        @Result(column="low", property="low", jdbcType=JdbcType.DECIMAL),
        @Result(column="close", property="close", jdbcType=JdbcType.DECIMAL),
        @Result(column="volume", property="volume", jdbcType=JdbcType.INTEGER),
        @Result(column="amount", property="amount", jdbcType=JdbcType.INTEGER)
    })
    MarketTradeDaily selectByPrimaryKey(@Param("tradedate") Date tradedate, @Param("codeid") String codeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketTradeDailySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MarketTradeDaily record, @Param("example") MarketTradeDailyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketTradeDailySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MarketTradeDaily record, @Param("example") MarketTradeDailyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    @UpdateProvider(type=MarketTradeDailySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MarketTradeDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market_tradedaily
     *
     * @mbg.generated
     */
    @Update({
        "update market_tradedaily",
        "set open = #{open,jdbcType=DECIMAL},",
          "high = #{high,jdbcType=DECIMAL},",
          "low = #{low,jdbcType=DECIMAL},",
          "close = #{close,jdbcType=DECIMAL},",
          "volume = #{volume,jdbcType=INTEGER},",
          "amount = #{amount,jdbcType=INTEGER}",
        "where tradedate = #{tradedate,jdbcType=DATE}",
          "and codeid = #{codeid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(MarketTradeDaily record);
}